# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: replica.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rreplica.proto\x12\x07\x62\x61\x63kupr\",\n\x0eReplicaDetails\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0c\n\x04\x61\x64\x64r\x18\x02 \x01(\t\"\x1f\n\rRequestStatus\x12\x0e\n\x06status\x18\x01 \x01(\x08\"a\n\x0cWriteDetails\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\x12\x0c\n\x04uuid\x18\x03 \x01(\t\x12\x0f\n\x07version\x18\x04 \x01(\t\x12\x13\n\x0bprimary_hop\x18\x05 \x01(\x08\"]\n\rWriteResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x03 \x01(\t\x12\x0c\n\x04uuid\x18\x04 \x01(\t\x12\x0f\n\x07version\x18\x05 \x01(\t\"\x1b\n\x0bReadDetails\x12\x0c\n\x04uuid\x18\x01 \x01(\t\"N\n\x0cReadResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x03 \x01(\t\x12\x0f\n\x07version\x18\x04 \x01(\t\"C\n\rDeleteDetails\x12\x0c\n\x04uuid\x18\x01 \x01(\t\x12\x0f\n\x07version\x18\x02 \x01(\t\x12\x13\n\x0bprimary_hop\x18\x03 \x01(\x08\" \n\x0e\x44\x65leteResponse\x12\x0e\n\x06status\x18\x01 \x01(\t2\x94\x02\n\x07Replica\x12\x46\n\x11UpdateReplicaList\x12\x17.backupr.ReplicaDetails\x1a\x16.backupr.RequestStatus\"\x00\x12?\n\x0cWriteRequest\x12\x15.backupr.WriteDetails\x1a\x16.backupr.WriteResponse\"\x00\x12<\n\x0bReadRequest\x12\x14.backupr.ReadDetails\x1a\x15.backupr.ReadResponse\"\x00\x12\x42\n\rDeleteRequest\x12\x16.backupr.DeleteDetails\x1a\x17.backupr.DeleteResponse\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'replica_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _REPLICADETAILS._serialized_start=26
  _REPLICADETAILS._serialized_end=70
  _REQUESTSTATUS._serialized_start=72
  _REQUESTSTATUS._serialized_end=103
  _WRITEDETAILS._serialized_start=105
  _WRITEDETAILS._serialized_end=202
  _WRITERESPONSE._serialized_start=204
  _WRITERESPONSE._serialized_end=297
  _READDETAILS._serialized_start=299
  _READDETAILS._serialized_end=326
  _READRESPONSE._serialized_start=328
  _READRESPONSE._serialized_end=406
  _DELETEDETAILS._serialized_start=408
  _DELETEDETAILS._serialized_end=475
  _DELETERESPONSE._serialized_start=477
  _DELETERESPONSE._serialized_end=509
  _REPLICA._serialized_start=512
  _REPLICA._serialized_end=788
# @@protoc_insertion_point(module_scope)
