# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: registryserver.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14registryserver.proto\x12\x08\x62\x61\x63kuprs\"$\n\rClientDetails\x12\x13\n\x0b\x63lient_uuid\x18\x01 \x01(\t\"\x1f\n\rRequestStatus\x12\x0e\n\x06status\x18\x01 \x01(\x08\",\n\x0eReplicaDetails\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0c\n\x04\x61\x64\x64r\x18\x02 \x01(\t\"=\n\x0bReplicaList\x12.\n\x0creplica_list\x18\x01 \x03(\x0b\x32\x18.backuprs.ReplicaDetails2\xad\x02\n\x0eRegistryServer\x12\x46\n\x0fRegisterReplica\x12\x18.backuprs.ReplicaDetails\x1a\x17.backuprs.RequestStatus\"\x00\x12\x42\n\x0eGetReplicaList\x12\x17.backuprs.ClientDetails\x1a\x15.backuprs.ReplicaList\"\x00\x12\x46\n\x12GetReadReplicaList\x12\x17.backuprs.ClientDetails\x1a\x15.backuprs.ReplicaList\"\x00\x12G\n\x13GetWriteReplicaList\x12\x17.backuprs.ClientDetails\x1a\x15.backuprs.ReplicaList\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'registryserver_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CLIENTDETAILS._serialized_start=34
  _CLIENTDETAILS._serialized_end=70
  _REQUESTSTATUS._serialized_start=72
  _REQUESTSTATUS._serialized_end=103
  _REPLICADETAILS._serialized_start=105
  _REPLICADETAILS._serialized_end=149
  _REPLICALIST._serialized_start=151
  _REPLICALIST._serialized_end=212
  _REGISTRYSERVER._serialized_start=215
  _REGISTRYSERVER._serialized_end=516
# @@protoc_insertion_point(module_scope)
