# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import registryserver_pb2 as registryserver__pb2


class RegistryServerStub(object):
    """Registry server messages
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterReplica = channel.unary_unary(
                '/backuprs.RegistryServer/RegisterReplica',
                request_serializer=registryserver__pb2.ReplicaDetails.SerializeToString,
                response_deserializer=registryserver__pb2.ReplicaDetails.FromString,
                )
        self.GetReplicaList = channel.unary_unary(
                '/backuprs.RegistryServer/GetReplicaList',
                request_serializer=registryserver__pb2.Empty.SerializeToString,
                response_deserializer=registryserver__pb2.ReplicaDetails.FromString,
                )
        self.GetPrimaryReplica = channel.unary_unary(
                '/backuprs.RegistryServer/GetPrimaryReplica',
                request_serializer=registryserver__pb2.Empty.SerializeToString,
                response_deserializer=registryserver__pb2.ReplicaDetails.FromString,
                )


class RegistryServerServicer(object):
    """Registry server messages
    """

    def RegisterReplica(self, request, context):
        """Registers a replica as well as sends the details of primary replica
        Registers as primary replica if none exists
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetReplicaList(self, request, context):
        """Returns List of replica's and their addresses
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPrimaryReplica(self, request, context):
        """Returns the primary replica details 
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RegistryServerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegisterReplica': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterReplica,
                    request_deserializer=registryserver__pb2.ReplicaDetails.FromString,
                    response_serializer=registryserver__pb2.ReplicaDetails.SerializeToString,
            ),
            'GetReplicaList': grpc.unary_unary_rpc_method_handler(
                    servicer.GetReplicaList,
                    request_deserializer=registryserver__pb2.Empty.FromString,
                    response_serializer=registryserver__pb2.ReplicaDetails.SerializeToString,
            ),
            'GetPrimaryReplica': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPrimaryReplica,
                    request_deserializer=registryserver__pb2.Empty.FromString,
                    response_serializer=registryserver__pb2.ReplicaDetails.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'backuprs.RegistryServer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class RegistryServer(object):
    """Registry server messages
    """

    @staticmethod
    def RegisterReplica(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/backuprs.RegistryServer/RegisterReplica',
            registryserver__pb2.ReplicaDetails.SerializeToString,
            registryserver__pb2.ReplicaDetails.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetReplicaList(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/backuprs.RegistryServer/GetReplicaList',
            registryserver__pb2.Empty.SerializeToString,
            registryserver__pb2.ReplicaDetails.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetPrimaryReplica(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/backuprs.RegistryServer/GetPrimaryReplica',
            registryserver__pb2.Empty.SerializeToString,
            registryserver__pb2.ReplicaDetails.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
