# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: replica.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rreplica.proto\x12\x07\x62\x61\x63kupr\",\n\x0eReplicaDetails\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0c\n\x04\x61\x64\x64r\x18\x02 \x01(\t\"\x1f\n\rRequestStatus\x12\x0e\n\x06status\x18\x01 \x01(\x08\x32Q\n\x07Replica\x12\x46\n\x11UpdateReplicaList\x12\x17.backupr.ReplicaDetails\x1a\x16.backupr.RequestStatus\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'replica_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _REPLICADETAILS._serialized_start=26
  _REPLICADETAILS._serialized_end=70
  _REQUESTSTATUS._serialized_start=72
  _REQUESTSTATUS._serialized_end=103
  _REPLICA._serialized_start=105
  _REPLICA._serialized_end=186
# @@protoc_insertion_point(module_scope)
