# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mapper.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cmapper.proto\x12\x07mappers\"L\n\x13ProcessFilesRequest\x12\x11\n\tfilenames\x18\x01 \x03(\t\x12\x0c\n\x04task\x18\x02 \x01(\t\x12\x14\n\x0cnum_reducers\x18\x03 \x01(\x05\"(\n\x14ProcessFilesResponse\x12\x10\n\x08response\x18\x01 \x01(\x08\x32W\n\x06Mapper\x12M\n\x0cProcessFiles\x12\x1c.mappers.ProcessFilesRequest\x1a\x1d.mappers.ProcessFilesResponse\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'mapper_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PROCESSFILESREQUEST._serialized_start=25
  _PROCESSFILESREQUEST._serialized_end=101
  _PROCESSFILESRESPONSE._serialized_start=103
  _PROCESSFILESRESPONSE._serialized_end=143
  _MAPPER._serialized_start=145
  _MAPPER._serialized_end=232
# @@protoc_insertion_point(module_scope)
