# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import mapper_pb2 as mapper__pb2


class MapperStub(object):
    """Server queries
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ProcessFiles = channel.unary_unary(
                '/mappers.Mapper/ProcessFiles',
                request_serializer=mapper__pb2.ProcessFilesRequest.SerializeToString,
                response_deserializer=mapper__pb2.ProcessFilesResponse.FromString,
                )
        self.ReturnKV = channel.unary_unary(
                '/mappers.Mapper/ReturnKV',
                request_serializer=mapper__pb2.ReducerID.SerializeToString,
                response_deserializer=mapper__pb2.KV.FromString,
                )


class MapperServicer(object):
    """Server queries
    """

    def ProcessFiles(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReturnKV(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MapperServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ProcessFiles': grpc.unary_unary_rpc_method_handler(
                    servicer.ProcessFiles,
                    request_deserializer=mapper__pb2.ProcessFilesRequest.FromString,
                    response_serializer=mapper__pb2.ProcessFilesResponse.SerializeToString,
            ),
            'ReturnKV': grpc.unary_unary_rpc_method_handler(
                    servicer.ReturnKV,
                    request_deserializer=mapper__pb2.ReducerID.FromString,
                    response_serializer=mapper__pb2.KV.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'mappers.Mapper', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Mapper(object):
    """Server queries
    """

    @staticmethod
    def ProcessFiles(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/mappers.Mapper/ProcessFiles',
            mapper__pb2.ProcessFilesRequest.SerializeToString,
            mapper__pb2.ProcessFilesResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ReturnKV(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/mappers.Mapper/ReturnKV',
            mapper__pb2.ReducerID.SerializeToString,
            mapper__pb2.KV.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
