# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: reducer.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rreducer.proto\x12\x08reducers\"4\n\x13ProcessFilesRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0f\n\x07version\x18\x02 \x01(\x05\"(\n\x14ProcessFilesResponse\x12\x10\n\x08response\x18\x01 \x01(\x08\x32Z\n\x07Reducer\x12O\n\x0cProcessFiles\x12\x1d.reducers.ProcessFilesRequest\x1a\x1e.reducers.ProcessFilesResponse\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'reducer_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PROCESSFILESREQUEST._serialized_start=27
  _PROCESSFILESREQUEST._serialized_end=79
  _PROCESSFILESRESPONSE._serialized_start=81
  _PROCESSFILESRESPONSE._serialized_end=121
  _REDUCER._serialized_start=123
  _REDUCER._serialized_end=213
# @@protoc_insertion_point(module_scope)
