# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: registryserver.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14registryserver.proto\x12\x07pubsubr\"\x84\x01\n\x15RegistryServerMessage\x12/\n\rclientDetails\x18\x01 \x01(\x0b\x32\x16.pubsubr.ClientDetailsH\x00\x12/\n\rserverDetails\x18\x02 \x01(\x0b\x32\x16.pubsubr.ServerDetailsH\x00\x42\t\n\x07\x44\x65tails\"$\n\rClientDetails\x12\x13\n\x0b\x63lient_uuid\x18\x01 \x01(\t\"+\n\rServerDetails\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0c\n\x04\x61\x64\x64r\x18\x02 \x01(\t\"%\n\x10StatusOfRegistry\x12\x11\n\tconnected\x18\x01 \x01(\x08\"9\n\nServerList\x12+\n\x0bserver_list\x18\x01 \x03(\x0b\x32\x16.pubsubr.ServerDetailsb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'registryserver_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _REGISTRYSERVERMESSAGE._serialized_start=34
  _REGISTRYSERVERMESSAGE._serialized_end=166
  _CLIENTDETAILS._serialized_start=168
  _CLIENTDETAILS._serialized_end=204
  _SERVERDETAILS._serialized_start=206
  _SERVERDETAILS._serialized_end=249
  _STATUSOFREGISTRY._serialized_start=251
  _STATUSOFREGISTRY._serialized_end=288
  _SERVERLIST._serialized_start=290
  _SERVERLIST._serialized_end=347
# @@protoc_insertion_point(module_scope)
